[workspace]
members = [
  "main",
  "mechtron",
  "mechtron_core",
  "mechtron_common",

  "mechtronium",
  "mechtronium_system",
  "mechtronium_server",
  "mechtronium_ext_web",
  "mechtronium_ext_local_filesystem",
  ]
